<?php

namespace MorningTrain\Laravel\Resources\Support\Contracts;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Str;
use MorningTrain\Laravel\Fields\Traits\ValidatesFields;
use MorningTrain\Laravel\Filters\Filters\FilterCollection;
use MorningTrain\Laravel\Resources\Http\Controllers\ResourceController;
use MorningTrain\Laravel\Support\Traits\StaticCreate;

abstract class PageOperation extends Operation
{

    public function prepare($parameters)
    {
        parent::prepare($parameters); // TODO: Change the autogenerated stub
    }

    public function execute()
    {
        return parent::execute(); // TODO: Change the autogenerated stub
    }

    public function handle($model_or_collection = null)
    {
        return parent::handle($model_or_collection); // TODO: Change the autogenerated stub
    }

    public function export()
    {
        return [];
    }

    public function path($value = null)
    {
        return $this->genericGetSet('path', $value);
    }

    public function getRoutePath()
    {
        return $this->path();
    }

}
